#pragma once


// PHYSICS

enum {
	// collision shapes
	CONSTRAINT_SPHERE,
	CONSTRAINT_CYLINDER,
	CONSTRAINT_CIRCLE,
	CONSTRAINT_CONE,
	CONSTRAINT_RIGHT_TRI_PRISM,
	CONSTRAINT_BOX,
	CONSTRAINT_RECT,
	CONSTRAINT_SEGMENT,
	CONSTRAINT_PLANE,
	CONSTRAINT_LINE,
	CONSTRAINT_RAY,

#define IS_SHAPE(t) ((t) <= CONSTRAINT_RAY)

	// joints
	CONSTRAINT_DISTANCE,
	CONSTRAINT_SPRING,
};

#define COMP_CONSTRAINT_ACTIVE 0x1

#define COMP_CHILD_OFFSET 0x1

#define COMP_GUI_PIXEL_POS 0x1
#define COMP_GUI_PIXEL_SCALE 0x2
#define COMP_GUI_PIXEL_ANCHOR 0x4

#define COMP_SOUND_GEN 0x1
#define COMP_SOUND_LOOP 0x2